services:
  db:
    image: postgres:16-alpine
    container_name: jobboard-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobboard
    ports:
      - "5433:5432"          # we changed this
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: